name: GPClaimGUI
version: 1.0.0
main: dev.claimgui.Main
api-version: '1.21'
authors: [ClaimGUI]

depend:
  - PlaceholderAPI

softdepend:
  - GriefPrevention

commands:
  claim-gui:
    description: Claim GUI aç
    permission: claim.gui
  claimgonder_ac:
    description: Blok gönder
    permission: claim.gui
  claimal_ac:
    description: Blok satın al
    permission: claim.gui
  claimtrust_ac:
    description: Yetkili ekle
    permission: claim.gui
  gpclaim-reload:
    description: Claim verilerini yenile
    permission: claim.admin

permissions:
  claim.gui:
    default: true
  claim.admin:
    default: op
